.github/workflows/build.yml
.github/workflows/tests.yml
.gitignore
jest.config.ts
package-lock.json
package.json
run_tests.sh
src/index.ts
tests/test.ts

tests(continuous-integration): Add continuous integration

---

README.md
doc/databases/users.dbml
package-lock.json
package.json
tsconfig.json

doc(databases): Add users database documentation

---

.github/workflows/ci.yml
Dockerfile
databases/Dockerfile
databases/Prophecy_Users.sql
doc/databases/users.dbml
docker-compose.yml

feat(databases/users): Add Prophecy_Users database

---

src/account/account.controller.ts
src/account/profile/profile.service.ts
tests/api/account/account.spec.ts

feat(account/settings/delete-acount): Add delete accound route

---

src/account/account.controller.ts
tests/api/account/account.spec.ts

feat(account/settings): Add update-username route + tests

---

.github/workflows/deploy.yml
package.json
src/account/account.module.ts
src/app.module.ts
src/database/prophecy.datasource.ts
tests/account/profile/profile.service.spec.ts
yarn.lock

The backend services (server + database) need to be deployed
CI addition to deploy on push on master branch
---
Closes #38

feat: Add backend deployment

---

src/army/ArmyCredentials.ts
src/army/army.controller.ts
src/army/army.entity.ts

The route `/armies/lookup` was returning all armies data instead of credentials only
Added an iteration on the data to extract credentials.
Also made the load method public to increase the route's rapidity
---
Closes #60

fix(armies): Fix armies/lookup return value

---

src/app.module.ts
src/heartbeat/heartbeat.controller.ts
src/heartbeat/heartbeat.module.ts

No way to know if the api is running
Added a `/heartbeat` route that returns 2000
---
closes #76

feat(heartbeat): Add heartbeat route

---

src/army-list/army-list-rule/army-list-rule.service.ts
src/army-list/army-list-unit/army-list-unit.service.ts
src/army-list/army-list-upgrade/army-list-upgrade.service.ts
src/army-list/army-list.controller.ts
src/army-list/army-list.service.ts

There was no way to update an army list
Added the `update` route
---
closes #63

Feat 63 update armies lists

---

src/account/profile/profile.entity.ts
src/army-list/army-list.controller.ts
src/army-list/army-list.dto.ts
src/army-list/army-list.service.ts
src/database/migration/1667924495954-Initialization.ts
tests/api/army-list/army-list.spec.ts

Army list tests were not working
fixed the queries

feat(army lists): Add update route

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
doc/api/api-swagger.yml
src/app.module.ts
src/army-list/army-list-unit/army-list-unit.entity.ts
src/army/unit/troop/troop.entity.ts
src/database/migration/1672323186772-ArmyListsInitialization.ts
src/database/migration/1672968324920-ProphecyUnitInitialization.ts
src/database/migration/ormconfig.ts
src/prophecy/prophecy.controller.ts
src/prophecy/prophecy.module.ts
src/prophecy/unit/prophecy-unit-maths.dto.ts
src/prophecy/unit/prophecy-unit.dto.ts
src/prophecy/unit/prophecy-unit.entity.ts
src/prophecy/unit/prophecy-unit.service.ts
yarn.lock

There was no link between the math library and the backend and the user was unable to request a prophecy
added a route to request a prophecy for units
---
closes #65 #66

Feat 65 66 retrieve and store prophecies

---

doc/api/api-swagger.yml
src/army-list/army-list-credentials.dto.ts
src/army-list/army-list.controller.ts
src/army-list/army-list.dto.ts
src/army-list/army-list.entity.ts
src/army-list/army-list.service.ts
tests/api/army-list/army-list.spec.ts

There was a typo in the army list controller params
fixed the typo
---
Closes [issue(s)]

fix: army lists controller

---

.github/workflows/tests.yml
tests/api/army-list/army-list.spec.ts
tests/api/army/army.spec.ts
tests/api/prophecy/prophecy.spec.ts

Could not run armies related tests because of database connection
Setup tests database

fix(ci): Add tests database connection & fix armies lists tests

---

src/account/account.controller.ts
src/account/account.module.ts
src/account/profile/profile.module.ts
src/email/email.module.ts
src/email/password-update.service.ts

The user had no confirmation of password change
Send an email when the password is updated
---
Closes #104

feat(account/password-update): Send email when user changes password

---

src/database/migration/1687856012071-GamesInitialization.ts
src/database/migration/ormconfig.ts
src/game/game.entity.ts

There was no database for games
Added games database migration & entity
---
Closes #107

feat(games): Add games migration and entity

---

doc/api/api-swagger.yml
src/app.module.ts
src/army-list/army-list.module.ts
src/game/game.controller.ts
src/game/game.module.ts
src/game/game.service.ts
tests/api/army-list/army-list.spec.ts
tests/api/game/game.spec.ts
tests/fixtures/army-list/armies-lists.ts
tests/tests.helper.ts
yarn.lock

there was no way to create games
Added the route to create a game
---
Closes #108

Feat games creation

---

src/app.module.ts
src/database/migration/1688721594196-ProphecyArmyInitialization.ts
src/database/migration/ormconfig.ts
src/prophecy/army/prophecy-army.entity.ts

There was no database table for army vs army prophecies
Added the table in the database migrations
---
Closes #101

feat(prophecies/armies): Add database migration and entity

---

src/prophecy/unit/prophecy-unit-maths.dto.ts

Nan type when non number stings where converted for math stats dto
Added a function to parse

feat(prophecies/units): Fix non number strings on stats conversion

---

src/email/email.service.ts

AWS SDK needed to be updated in email service 
Updated version and updated SES config

fix(email): Update aws sdk version

---

src/army-list/army-list-unit/army-list-unit.module.ts
src/army-list/army-list-unit/army-list-unit.service.ts
src/army-list/army-list-unit/magic-item/army-list-unit-magic-item.service.ts
src/army-list/army-list-unit/magic-standard/army-list-unit-magic-standard.service.ts
src/army-list/army-list-unit/option/army-list-unit-option.service.ts
src/army-list/army-list-unit/troop/equipment/army-list-unit-troop-equipment.service.ts
src/army-list/army-list-unit/troop/special-rule/army-list-unit-troop-special-rule.service.ts
src/army-list/army-list.controller.ts
src/army-list/army-list.module.ts
src/prophecy/prophecy.controller.ts
src/prophecy/prophecy.module.ts
src/prophecy/unit/prophecy-unit.entity.ts
src/prophecy/unit/prophecy-unit.service.ts
tests/api/army-list/delete.spec.ts
tests/api/army-list/get.spec.ts
tests/api/army-list/lookup.spec.ts
tests/api/army-list/update.spec.ts
tests/api/prophecy/prophecy.spec.ts
tests/helper/army-list.helper.ts

Bugs occured after relations refactoring in army list units
Updated the code & tests

Fix update prophecy unit

---

.github/workflows/tests.yml
src/app.module.ts
src/database/migration/1688721594196-ProphecyArmyInitialization.ts
src/database/migration/ormconfig.ts
src/prophecy/army/prophecy-army.entity.ts

Needed to store prophecies armies
updated database to store prophecies armies

Prophecies armies

---

src/prophecy/maths/prophecy-maths.dto.ts
src/prophecy/maths/prophecy-maths.service.ts
src/prophecy/maths/prophecy-unit-maths.dto.ts
src/prophecy/prophecy.controller.ts
src/prophecy/unit/prophecy-unit.entity.ts
tests/api/prophecy/prophecy.spec.ts

Modifiers were not used in unit prophecies
Added modifiers
---
Closes #100

feat(prophecies/units): Add modifiers in maths request

---

doc/api/api-swagger.yml
src/army/unit/unit.entity.ts
src/database/prophecy.datasource.ts
src/prophecy/army/prophecy-army.service.ts
src/prophecy/prophecy.controller.ts
tests/api/prophecy/army/create.spec.ts
tests/api/prophecy/army/lookup.spec.ts

There was no route to retrieve prophecies army history
implemented the route
---
Closes #106

feat(prophecies/armies): Add lookup route

---

doc/api/api-swagger.yml
src/prophecy/army/prophecy-army.service.ts
src/prophecy/prophecy.controller.ts
tests/api/prophecy/army/delete.spec.ts

There was no route to delete an armies prophecies
implemented the route
---
Closes #132

feat(prophecies/armies): Add delete route

---

doc/api/api-swagger.yml
src/game/game.controller.ts
src/game/game.service.ts
tests/api/game/delete.spec.ts

No route to delete games
Added route
---
Closes #135

feat(games): Add delete route

---

doc/api/api-swagger.yml
src/account/account.controller.ts

No route to retrieve the profile's data
Added the route

feat(account): Add profile data retrievment

---

src/account/account.controller.ts
src/account/profile/profile.entity.ts
tests/api/account/delete.spec.ts
tests/api/account/update-email.spec.ts
tests/api/account/update-password.spec.ts
tests/api/account/update-username.spec.ts
tests/api/app/sign-in.spec.ts
tests/api/app/sign-out.spec.ts
tests/api/app/sign-up.spec.ts
tests/api/army-list/create.spec.ts
tests/api/army-list/delete.spec.ts
tests/api/army-list/get.spec.ts
tests/api/army-list/lookup.spec.ts
tests/api/army-list/update.spec.ts
tests/api/game/create.spec.ts
tests/api/game/delete.spec.ts
tests/api/game/lookup.spec.ts
tests/api/prophecy/army/create.spec.ts
tests/api/prophecy/army/delete.spec.ts
tests/api/prophecy/army/lookup.spec.ts
tests/api/prophecy/units/create.spec.ts
tests/api/prophecy/units/delete.spec.ts
tests/api/prophecy/units/lookup.spec.ts
tests/tests.helper.ts

There was no password verification to delete a user's account
Added the password comparison in the route implementation
---
Closes #140

feat(accound/delete): Add password in route parameter

---

src/army/unit/unit.entity.ts

Missing data on army request
Rolled back to keep the after load function

Fix armies route missing data

---

src/account/account.controller.ts
tests/api/account/update-username.spec.ts

The user's armies lists were not deleted on account deletion
Delete armies lists on account deletion
---
close #141

Fix 141 delete armies lists on account deletion

---

src/prophecy/maths/prophecy-army-maths.dto.ts

*Describe the problem you fixed here*
*Describe the changements here*
---
Closes [issue(s)]

feat(prophecies): implement new math DTO
